
SELECT [NOME] AS IDENTIFIACDOR, [MATRICULA]

	FROM [TABELA DE VENDEDORES] 


SELECT * FROM [TABELA DE VENDEDORES] WHERE [NOME] ='Roberta Martins'

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 5.18

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM >= 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'Lata'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 5.18

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIEMNTO] = '1990-10-25'


