
DECLARE @IDADE INT
DECLARE @NOME VARCHAR(200)
DECLARE @DATA DATE

DECLARE @IDADE2 INT, @NOME2 VARCHAR(200), @DATA2 DATE

SET @IDADE = 20
--PRINT @IDADE

SET @NOME = 'JOÃO DA SILVA'
--PRINT @NOME

SET @DATA = '20180517'
--PRINT @DATA

DECLARE @CPF VARCHAR(12)
SET @CPF = '2600586709'

--SELECT NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES]
--WHERE CPF = @CPF

SELECT @NOME2 = NOME, @DATA2 = [DATA DE NASCIMENTO], @IDADE2 = IDADE 
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF

PRINT @NOME2
PRINT @DATA2
PRINT @IDADE2


DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)

SET @MATRICULA = '00240'
SET @NOME = 'Cláudia Rodrigues'
SET @PERCENTUAL = 0.10
SET @DATA = '20120312'
SET @FERIAS = 1
SET @BAIRRO = 'Jardins'

INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO]
, [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

SELECT * FROM [TABELA DE VENDEDORES]


DECLARE @Cliente VARCHAR(10)
DECLARE @Idade INT
DECLARE @DataNascimento DATE
DECLARE @Custo FLOAT
SET @Cliente = 'João'
SET @Idade = 10
SET @DataNascimento = '20170110'
SET @Custo = 10.23
PRINT @Cliente
PRINT @Idade
PRINT @DataNascimento
PRINT @Custo


DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101'
PRINT @NUMNOTAS


