SELECT * FROM PRODUTOS

UPDATE [PRODUTOS] SET [PREÇO LISTA] = 5
WHERE [CÓDIGO] = '1040107'

UPDATE [PRODUTOS] SET [SABOR] = 'Laranja', [EMBALAGEM] = 'PET'
WHERE [CÓDIGO] = '1040107'

SELECT * FROM PRODUTOS WHERE [SABOR] = 'Maracujá'

UPDATE [PRODUTOS] SET [PREÇO LISTA] = [PREÇO LISTA] * 1.10
WHERE [SABOR] = 'Maracujá'

SELECT * FROM PRODUTOS WHERE [SABOR] = 'Maracujá' 


UPDATE [dbo].[CLIENTES] SET 
    [ENDEREÇO] = 'R. Jorge Emilio 23',
    [BAIRRO] = 'Santo Amaro',
    [CIDADE] = 'São Paulo',
    [ESTADO] = 'SP',
    [CEP] = '8833223'
WHERE [CPF] = '19290992743'

