
CREATE DATABASE [VENDAS SUCOS]

CREATE DATABASE [VENDAS SUCOS 2]
ON (NAME = VENDAS_SUCOS_2_DAT,
FILENAME = 'C:\TEMP\DATA\VENDAS_SUCOS_02.MDF',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5)
LOG ON (NAME = VENDAS_SUCOS_2_LOG,
FILENAME = 'C:\TEMP\DATA\VENDAS_SUCOS_02.LDF',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5)

DROP DATABASE [VENDAS SUCOS 2]


CREATE TABLE [PRODUTOS]
([CÓDIGO] VARCHAR(10) NOT NULL,
[DESCRITOR] VARCHAR(100) NULL,
[SABOR] VARCHAR(50) NULL,
[TAMANHO] VARCHAR(50) NULL,
[EMBALAGEM] VARCHAR(50) NULL,
[PREÇO LISTA] FLOAT NULL,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO]))

CREATE TABLE [VENDEDORES]
([MATRÍCULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[BAIRRO] VARCHAR(50) NULL,
[COMISSÃO] FLOAT NULL,
[DATA ADMISSÃO] DATE NULL,
[FÉRIAS] BIT NULL,
CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA]))

CREATE TABLE [dbo].[CLIENTES](
    [CPF] VARCHAR(11) NOT NULL,
    [NOME] VARCHAR(50) NULL,
    [ENDEREÇO] VARCHAR(100) NULL,
    [BAIRRO] VARCHAR(50) NULL,
    [CIDADE] VARCHAR(50) NULL,
    [ESTADO] VARCHAR(50) NULL,
    [CEP] VARCHAR(8) NULL,
    [DATA NASCIMENTO] DATE NULL,
    [IDADE] INT NULL,
    [SEXO] VARCHAR(1),
    [LIMITE DE CRÉDITO] FLOAT,
    [VOLUME DE COMPRA] FLOAT,
    [PRIMEIRA COMPRA] BIT, 
    CONSTRAINT [PK_CLIENTES] 
        PRIMARY KEY CLUSTERED ([CPF])
)

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY ([CPF]) REFERENCES [CLIENTES] ([CPF])

USE [VENDAS SUCOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITENS VENDIDOS](
    [NÚMERO] VARCHAR(5) NOT NULL,
    [CÓDIGO] VARCHAR(10) NOT NULL,
    [QUANTIDADE] INT NULL,
    [PREÇO] FLOAT NULL, 
CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED (
    [NÚMERO] ASC, [CÓDIGO] ASC
) WITH (
    PAD_INDEX = OFF, 
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = OFF, 
    ALLOW_ROW_LOCKS = ON, 
    ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  
CONSTRAINT [FK_ITENS VENDIDOS_NOTAS] FOREIGN KEY([NÚMERO])
REFERENCES [dbo].[NOTAS] ([NÚMERO])
GO

ALTER TABLE [dbo].[ITENS VENDIDOS] 
CHECK CONSTRAINT [FK_ITENS VENDIDOS_NOTAS]
GO

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  
CONSTRAINT [FK_ITENS VENDIDOS_TABELA DE PRODUTOS] FOREIGN KEY([CÓDIGO])
REFERENCES [dbo].[TABELA DE PRODUTOS] ([CÓDIGO])
GO

ALTER TABLE [dbo].[ITENS VENDIDOS] 
CHECK CONSTRAINT [FK_ITENS VENDIDOS_TABELA DE PRODUTOS]
GO







