/** Usando Select no controle fluxo **/

SELECT * FROM [TABELA DE CLIENTES]
SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Água Santa'

DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Água Santa'
SET @LIMITE_MAXIMO = 50000
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO
IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
BEGIN
   PRINT 'Valor estourou. Não é possível abrir novos créditos'
END
ELSE
BEGIN
   PRINT 'Valor não estourou. É possível abrir novos créditos'
END


DECLARE @DATANOTA DATE
SET @DATANOTA = '20170102'
IF (SELECT COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATANOTA) > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'


/** Loop While **/

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @LIMITE_BREAK INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10
SET @LIMITE_BREAK = 12

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
   PRINT @LIMITE_MINIMO
   SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
   IF @LIMITE_MINIMO = @LIMITE_BREAK
   BEGIN
      PRINT 'Saindo por causa do BREAK'
      BREAK
   END
END

DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END


/**  Loop inserindo registros em tabela **/

IF OBJECT_ID ('TABELA DE NUMEROS','U') IS NOT NULL
   DROP TABLE [TABELA DE NUMEROS]

CREATE TABLE [TABELA DE NUMEROS] ([NUMERO] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
   SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MINIMO
   IF @CONTADOR_NOTAS > 0 
       INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal')
   ELSE
       INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal')
   SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1   
END

SELECT * FROM [TABELA DE NUMEROS]

IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
DROP TABLE TABELANOTAS
CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END
SELECT * FROM TABELANOTAS


/** inserindo registros em tabela temporaria **/

CREATE TABLE #TABELA01 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)

INSERT INTO #TABELA01 (ID, NOME) VALUES ('1', 'JOÃO')

SELECT * FROM #TABELA01

INSERT INTO #TABELA01 (ID, NOME) VALUES ('2', 'PEDRO')


CREATE TABLE ##TABELA02 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL)

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('1', 'JOÃO')

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('2', 'PEDRO')

SELECT * FROM ##TABELA02


DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @CONTADOR_NOTAS INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200))
CREATE TABLE #TABELA_NUMEROS2 ([NUMERO] INT, [STATUS] VARCHAR(200))

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
   SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MINIMO
   IF @CONTADOR_NOTAS > 0 
       BEGIN
          INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal')
	      INSERT INTO #TABELA_NUMEROS2 ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal')
	   END
   ELSE
       BEGIN
          INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal')
	      INSERT INTO #TABELA_NUMEROS2 ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal')
	   END
   SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1   
END

SELECT * FROM @TABELA_NUMEROS
SELECT * FROM #TABELA_NUMEROS2











